# Generated by Django 5.0.1 on 2025-07-28 19:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QCChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название чек-листа"),
                ),
                (
                    "material_grade",
                    models.CharField(
                        blank=True,
                        help_text="Оставьте пустым для универсального чек-листа",
                        max_length=100,
                        verbose_name="Марка материала (фильтр)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Версия"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чек-лист ОТК",
                "verbose_name_plural": "Чек-листы ОТК",
                "ordering": ["material_grade", "name"],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="QCChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("description", models.TextField(verbose_name="Описание пункта")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text='Критические пункты не могут быть отмечены как "Н/П"',
                        verbose_name="Критический пункт",
                    ),
                ),
                (
                    "acceptance_criteria",
                    models.TextField(
                        blank=True,
                        help_text="Подробное описание того, что считается приемлемым",
                        verbose_name="Критерии приемки",
                    ),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="quality.qcchecklist",
                        verbose_name="Чек-лист",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт чек-листа",
                "verbose_name_plural": "Пункты чек-листа",
                "ordering": ["checklist", "order"],
                "unique_together": {("checklist", "order")},
            },
        ),
        migrations.CreateModel(
            name="QCInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "inspection_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата инспекции"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "requires_ppsd",
                    models.BooleanField(default=False, verbose_name="Требует ППСД"),
                ),
                (
                    "requires_ultrasonic",
                    models.BooleanField(default=False, verbose_name="Требует УЗК"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инспектор",
                    ),
                ),
                (
                    "material_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_inspections",
                        to="warehouse.materialreceipt",
                        verbose_name="Поступление материала",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инспекция ОТК",
                "verbose_name_plural": "Инспекции ОТК",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="QCInspectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passed", "Пройдено"),
                            ("failed", "Не пройдено"),
                            ("na", "Не применимо"),
                        ],
                        max_length=10,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительные комментарии по результату проверки",
                        verbose_name="Примечания",
                    ),
                ),
                (
                    "measured_value",
                    models.CharField(
                        blank=True,
                        help_text="Фактическое измеренное значение (если применимо)",
                        max_length=100,
                        verbose_name="Измеренное значение",
                    ),
                ),
                (
                    "inspector_signature",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Подпись инспектора"
                    ),
                ),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_results",
                        to="quality.qcchecklistitem",
                        verbose_name="Пункт чек-листа",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_results",
                        to="quality.qcinspection",
                        verbose_name="Инспекция",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат инспекции",
                "verbose_name_plural": "Результаты инспекции",
                "ordering": ["checklist_item__order"],
            },
        ),
        migrations.AddIndex(
            model_name="qcinspection",
            index=models.Index(fields=["status"], name="quality_qci_status_17b661_idx"),
        ),
        migrations.AddIndex(
            model_name="qcinspection",
            index=models.Index(
                fields=["inspection_date"], name="quality_qci_inspect_1a3a01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qcinspection",
            index=models.Index(
                fields=["inspector"], name="quality_qci_inspect_c6c85a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qcinspectionresult",
            index=models.Index(fields=["result"], name="quality_qci_result_e38338_idx"),
        ),
        migrations.AddIndex(
            model_name="qcinspectionresult",
            index=models.Index(
                fields=["checklist_item"], name="quality_qci_checkli_d09e54_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="qcinspectionresult",
            unique_together={("inspection", "checklist_item")},
        ),
    ]
