# Generated by Django 4.2.7 on 2025-08-02 21:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        help_text="ID чата в Telegram для отправки уведомлений",
                        max_length=50,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Chat ID должен содержать только цифры",
                                regex="^-?\\d+$",
                            )
                        ],
                        verbose_name="Telegram Chat ID",
                    ),
                ),
                (
                    "is_telegram_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Включить Telegram уведомления"
                    ),
                ),
                (
                    "notification_types",
                    models.JSONField(
                        default=dict,
                        help_text="Настройки для каждого типа уведомлений",
                        verbose_name="Типы уведомлений",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Время начала периода, когда не отправлять уведомления",
                        null=True,
                        verbose_name="Начало тихих часов",
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="Время окончания периода, когда не отправлять уведомления",
                        null=True,
                        verbose_name="Конец тихих часов",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow",
                        max_length=50,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "English")],
                        default="ru",
                        max_length=10,
                        verbose_name="Язык уведомлений",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений пользователя",
                "verbose_name_plural": "Настройки уведомлений пользователей",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(max_length=50, verbose_name="Тип уведомления"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "telegram_chat_id",
                    models.CharField(max_length=50, verbose_name="Telegram Chat ID"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка отправки"),
                            ("retry", "Повторная попытка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество попыток"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время отправки"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тип объекта"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID объекта"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог уведомления",
                "verbose_name_plural": "Логи уведомлений",
                "ordering": ["-created_at"],
            },
        ),
    ]
