# Generated by Django 5.0.1 on 2025-07-28 19:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "material_grade",
                    models.CharField(max_length=100, verbose_name="Марка материала"),
                ),
                (
                    "supplier",
                    models.CharField(max_length=200, verbose_name="Поставщик"),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, verbose_name="Номер заказа"),
                ),
                (
                    "certificate_number",
                    models.CharField(max_length=100, verbose_name="Номер сертификата"),
                ),
                (
                    "heat_number",
                    models.CharField(max_length=100, verbose_name="Номер плавки"),
                ),
                ("size", models.CharField(max_length=100, verbose_name="Размер")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Количество"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Килограммы"),
                            ("pcs", "Штуки"),
                            ("meters", "Метры"),
                        ],
                        max_length=10,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "receipt_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата поступления",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Местоположение на складе",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="QR код",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="Внешний идентификатор",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Удалено пользователем",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="certificates/", verbose_name="PDF файл сертификата"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Извлеченные данные"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Размер файла (байт)"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Хеш файла"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="warehouse.material",
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "receipt_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата приемки"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="Номер документа"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_qc", "Ожидает ОТК"),
                            ("in_qc", "В ОТК"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending_qc",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="warehouse.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Принял",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поступление материала",
                "verbose_name_plural": "Поступления материалов",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["material_grade"], name="warehouse_m_materia_ac1b0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["supplier"], name="warehouse_m_supplie_10a2b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["certificate_number"], name="warehouse_m_certifi_eb97b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["heat_number"], name="warehouse_m_heat_nu_6f2aae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["receipt_date"], name="warehouse_m_receipt_4b9159_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialreceipt",
            index=models.Index(fields=["status"], name="warehouse_m_status_fa0ab1_idx"),
        ),
        migrations.AddIndex(
            model_name="materialreceipt",
            index=models.Index(
                fields=["receipt_date"], name="warehouse_m_receipt_dfe9a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialreceipt",
            index=models.Index(
                fields=["document_number"], name="warehouse_m_documen_5081ea_idx"
            ),
        ),
    ]
