# Generated by Django 4.2.7 on 2025-08-02 22:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("text_extraction", "Извлечение текста"),
                            ("data_parsing", "Парсинг данных"),
                            ("preview_generation", "Генерация превью"),
                            ("search_indexing", "Поисковая индексация"),
                        ],
                        max_length=50,
                        verbose_name="Операция",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Начата"),
                            ("completed", "Завершена"),
                            ("failed", "Ошибка"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время завершения"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Длительность (сек)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные операции"
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="warehouse.certificate",
                        verbose_name="Сертификат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог обработки",
                "verbose_name_plural": "Логи обработки",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificatePreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/previews/",
                        verbose_name="Превью изображение",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/thumbnails/",
                        verbose_name="Миниатюра",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата генерации"),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает генерации"),
                            ("generating", "Генерируется"),
                            ("completed", "Сгенерировано"),
                            ("failed", "Ошибка генерации"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус генерации",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "certificate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview",
                        to="warehouse.certificate",
                        verbose_name="Сертификат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Превью сертификата",
                "verbose_name_plural": "Превью сертификатов",
            },
        ),
        migrations.CreateModel(
            name="CertificateSearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True, verbose_name="Поисковый вектор"
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, verbose_name="Извлеченный текст"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Марка материала"
                    ),
                ),
                (
                    "heat_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер плавки"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер сертификата"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Поставщик"
                    ),
                ),
                (
                    "chemical_composition",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Химический состав"
                    ),
                ),
                (
                    "mechanical_properties",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Механические свойства"
                    ),
                ),
                (
                    "test_results",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Результаты испытаний"
                    ),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата индексации"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Обработан"),
                            ("failed", "Ошибка обработки"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус обработки",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "certificate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to="warehouse.certificate",
                        verbose_name="Сертификат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поисковый индекс сертификата",
                "verbose_name_plural": "Поисковые индексы сертификатов",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="certificate_search__534bbe_gin"
                    )
                ],
            },
        ),
    ]
