# Generated by Django 5.2.4 on 2025-08-09 09:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("viewflow", "0014_alter_process_parent_task"),
        ("warehouse", "0002_material_notes_alter_material_unit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialInspectionProcess",
            fields=[
                (
                    "process_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.process",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("normal", "Обычный"),
                            ("high", "Высокий"),
                            ("urgent", "Срочный"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время завершения"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок выполнения"
                    ),
                ),
                (
                    "sla_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SLA крайний срок"
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Процент выполнения",
                    ),
                ),
                (
                    "requires_ppsd",
                    models.BooleanField(default=False, verbose_name="Требует ППСД"),
                ),
                (
                    "requires_ultrasonic",
                    models.BooleanField(default=False, verbose_name="Требует УЗК"),
                ),
                (
                    "requires_production_prep",
                    models.BooleanField(
                        default=True, verbose_name="Требует подготовку к производству"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, verbose_name="Комментарии к процессу"),
                ),
                (
                    "escalation_notes",
                    models.TextField(blank=True, verbose_name="Заметки об эскалации"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "current_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_processes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Текущий исполнитель",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_processes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор процесса",
                    ),
                ),
                (
                    "material_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_process",
                        to="warehouse.materialreceipt",
                        verbose_name="Приемка материала",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Процесс инспекции материала",
                "verbose_name_plural": "Процессы инспекции материалов",
                "ordering": ["-created_at"],
            },
            bases=("viewflow.process", models.Model),
        ),
        migrations.CreateModel(
            name="WorkflowSLAViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("warning", "Предупреждение"),
                            ("critical", "Критическое"),
                            ("overdue", "Просрочено"),
                        ],
                        max_length=20,
                        verbose_name="Тип нарушения",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активное"),
                            ("acknowledged", "Принято к сведению"),
                            ("resolved", "Разрешено"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус нарушения",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время обнаружения"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время принятия"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время разрешения"
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение о нарушении")),
                (
                    "resolution_comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий к разрешению"
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_violations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Принято к сведению",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_violations",
                        to="workflow.materialinspectionprocess",
                        verbose_name="Процесс",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_violations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Разрешено пользователем",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Нарушение SLA",
                "verbose_name_plural": "Нарушения SLA",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "task_name",
                    models.CharField(max_length=100, verbose_name="Название задачи"),
                ),
                ("task_id", models.CharField(max_length=50, verbose_name="ID задачи")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("assigned", "Назначена"),
                            ("started", "Начата"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                            ("escalated", "Эскалирована"),
                            ("reassigned", "Переназначена"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время действия"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Длительность (сек)"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные данные"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_task_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначена на",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_logs",
                        to="workflow.materialinspectionprocess",
                        verbose_name="Процесс",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог задачи workflow",
                "verbose_name_plural": "Логи задач workflow",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="materialinspectionprocess",
            index=models.Index(
                fields=["priority", "-created_at"],
                name="workflow_ma_priorit_dd4f2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialinspectionprocess",
            index=models.Index(
                fields=["current_assignee"], name="workflow_ma_current_961054_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialinspectionprocess",
            index=models.Index(
                fields=["sla_deadline"], name="workflow_ma_sla_dea_72022d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowslaviolation",
            index=models.Index(
                fields=["status", "-detected_at"], name="workflow_wo_status_918fba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowslaviolation",
            index=models.Index(
                fields=["violation_type", "-detected_at"],
                name="workflow_wo_violati_5918d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtasklog",
            index=models.Index(
                fields=["process", "-timestamp"], name="workflow_wo_process_6f5141_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtasklog",
            index=models.Index(
                fields=["task_name", "-timestamp"],
                name="workflow_wo_task_na_d87fb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtasklog",
            index=models.Index(
                fields=["performer", "-timestamp"],
                name="workflow_wo_perform_999320_idx",
            ),
        ),
    ]
